### ISSUE TITLE
stoploss

### ISSUE THREAD

**Issue by qkum** [bybit-exchange/api-usage-examples#25]
funny how neither this repo or the pybit repo, or bybit API documentation shows how to implement stop-loss...

is it really true that the whole world of crypto is only trying to bankrupt you and run with your life savings?

wall street is at a much higher level. they are happy if they can just get pocket change out of you for the rest of your life.

https://github.com/bybit-exchange/api-usage-examples/blob/master/api_demo/futures/Encryption.py

**Comment by qkum** [comment]
putting a leverage/margin trade on without a stop-loss is worse than giving your money to the first homeless person you meet on the street.

on purpose avoiding showing people how to use stop-loss on a buy order is pure evil.

and how you do it 100% correctly & safely is the only way to do it. hacking together an error-prone solution will only lose you every penny again.

this is so dirty, it is clearly on purpose.

**Comment by dextertd** [comment]
You can find the `stop_loss` in the API documentation. It can be easily added to the examples hosted in the api-usage-examples repository.

<img width="853" alt="Screenshot 2022-08-23 at 12 28 57" src="https://user-images.githubusercontent.com/54495183/186146947-aca23b68-35cc-4296-b44d-51e088a1acfb.png">

pybit links to the API documentation, and you can pretty easily amend the python example shown there to set an SL with your order

```
from pybit import inverse_perpetual
session_auth = inverse_perpetual.HTTP(
    endpoint="https://api-testnet.bybit.com",
    api_key="your api key",
    api_secret="your api secret"
)
print(session_auth.place_active_order(
    symbol="BTCUSD",
    side="Buy",
    order_type="Market",
    qty=1,
    time_in_force="GoodTillCancel",
    stop_loss=15000  # <----------- just added this line
))
```
